'''
CREATE TABLE dbo.tTrocaDem(
ID INT PRIMARY KEY IDENTITY (1, 1),
ORDEM INT NOT NULL,
DEM_OUT INT NOT NULL,
DEM_IN INT NOT NULL,
DT_SOL DATETIME NOT NULL,
EFETUADO BIT DEFAULT 0,
DT_EXECUT DATETIME
);

CREATE TABLE dbo.tUsuarios(
NOME VARCHAR (50) NOT NULL,
NICKNAME VARCHAR (20) PRIMARY KEY NOT NULL,
SENHA VARCHAR (50) NOT NULL
);

INSERT INTO dbo.tTrocaDem (ORDEM, DEM_OUT, DEM_IN, DT_SOL, EFETUADO, DT_EXECUT)
VALUES
(1088758, 11865, 11866, SYSDATETIME(), 1, SYSDATETIME()),
(1088768, 11865, 11866, SYSDATETIME(), 1, SYSDATETIME());



SELECT * FROM dbo.tTrocaDem;
'''
